In [1]:
num_1 = 4
num_2 = 2
print(num_1 + num_2)
print(num_1 - num_2)

6
2


In [2]:
tupla_1 = (1, 2, 3)
tupla_2 = (1, 2, 3)
print (tupla_1 + tupla_2)

(1, 2, 3, 1, 2, 3)


In [3]:
tupla_1 += tupla_2
display(tupla_1)
display(tupla_2)

(1, 2, 3, 1, 2, 3)

(1, 2, 3)

In [4]:
list(tupla_1)

[1, 2, 3, 1, 2, 3]

In [5]:
dict_1 = {"a": 1, "b": 2}
dict_2 = {"a": 10, "b": 20}
dict_1 + dict_2

TypeError: unsupported operand type(s) for +: 'dict' and 'dict'

In [7]:
lista_tupla_1 = list(tupla_1)
lista_tupla_1

[1, 2, 3, 1, 2, 3]

In [23]:
lista_tupla_1 [2] += 2
lista_tupla_1

[1, 2, 35, 1, 2, 3]

In [24]:
import numpy as np

In [26]:
array = np.array(lista_tupla_1)
array

array([ 1,  2, 35,  1,  2,  3])

In [27]:
array += 2
array

array([ 3,  4, 37,  3,  4,  5])

In [28]:
array *= array
array

array([   9,   16, 1369,    9,   16,   25])

In [31]:
np.insert(arr=array, obj=2, values=100)

array([   9,   16,  100, 1369,    9,   16,   25])

In [37]:
array = np.array(lista_tupla_1).reshape(2, -1)
array

array([[ 1,  2, 35],
       [ 1,  2,  3]])

In [35]:
import pandas as pd

In [39]:
df = pd.DataFrame(array)
df

,0,1,2
0,1,2,35
1,1,2,3


In [42]:
array_ones = np.ones_like(df).reshape(3,2)
array_ones [1,1] = 100
array_ones

array([[  1,   1],
       [  1, 100],
       [  1,   1]])